name: 'velyon'
version: '1.0.0'
config-version: 2

Expand Down
Expand Up
	@@ -29,9 +32,7 @@ clean-targets:         # directories to be removed by `dbt clean`
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  velyon:
    # Applies to all files under models/example/
    staging:
      materialized: view
    int:
      materialized: view